
---
title: " Inference VGG-16 Pre-trained Model"
output: github_document
---

___Inference VGG-16 Pre-trained Model (ImageNet Challenge) using Keras___


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Init Keras
```{r init_keras, message=FALSE, warning=FALSE}
library(keras)
install_keras(tensorflow = "gpu") # WARN: uncomment if you want to train model with GPU
```



## Get files
WARN: save images locally and set <images_dir> explicitly 
```{r}
files <- dir("<images_dir>", pattern = ".jpg", full.names = T) 
print(files)

```


## Load model
```{r}
model <- application_vgg16(weights = "imagenet")
summary(model)

```


## Predict and evaluate
```{r}
output <- map(files,
              function(.f) {
                
                # convert image to numeric vector
                img <- image_load(.f, target_size = c(224, 224))
                x <- image_to_array(img)
                x <- array_reshape(x, dim = c(1, 224, 224, 3))
                x <- imagenet_preprocess_input(x)
                
                # predict
                pred <- model %>% predict(x)
                
                # evaluate
                imagenet_decode_predictions(pred, top = 3)[[1]]
              })
```


## References:
* https://arxiv.org/abs/1409.1556
